import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <main className={styles.main}>
        <h1 className={styles.title}>Micro Site para Asafe</h1>
      </main>
    </div>
  );
}
